<h2 style = "color : Brown"> Creating NumPy Arrays </h2 >



 The following ways are commonly used when you know the size of the array beforehand:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
import numpy as np

##### Tip: Use help to see the syntax when required

In [2]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

##### Creating a 1 D array of ones

In [3]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

##### Notice that, by default, numpy creates data type = float64



In [4]:
arr.dtype

dtype('float64')

##### Can provide dtype explicitly using dtype


In [5]:
arr = np.ones(5, dtype=int)
arr

array([1, 1, 1, 1, 1])

In [6]:
arr.dtype

dtype('int32')

##### Creating a 5  x 3 array of ones


In [7]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### Creating array of zeros

In [8]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [9]:
# convert the type into integer.
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [10]:
# Create a list of integers range between 1 to 5.
list(range(1,5))

[1, 2, 3, 4]

In [11]:
np.arange(300)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
np.arange(3.0)

array([0., 1., 2.])

##### Notice that 3 is included, 35 is not, as in standard python lists

From 3 to 35 with a step of 2

In [13]:
np.arange(3,35,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

##### Array of random numbers 


In [14]:
np.random.randint(2, size=10)

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0])

In [15]:
np.random.randint(3,5, size=10)

array([3, 3, 4, 4, 4, 3, 3, 4, 3, 4])

##### 2D Array of random numbers 


In [16]:
np.random.random([3,4])

array([[0.08905625, 0.86577428, 0.74318062, 0.37063088],
       [0.7219612 , 0.37785151, 0.39410814, 0.30540612],
       [0.2468836 , 0.06464738, 0.37517096, 0.77852438]])

###### Sometimes, you know the length of the array, not the step size

Array of length 20 between 1 and 10

In [17]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

<h2 style = "color : Sky blue"> Exercises </h2>



Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

In [18]:
import numpy as np, pandas

#Classes overview (instance methods, class methods, static methods)
from IPython.display import display,HTML
display(HTML('''
<h3>Stacking arrays in numpy</h3>
''')) 

In [27]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(np.hstack((a,b)))
print(np.vstack((a,b)))  # error when bith arrays are of different dimensions
print(np.hstack((np.hstack((a,b)),np.hstack((a,b)))))
print(np.hstack((np.vstack((a,b)),np.vstack((a,b)))))
print(np.vstack((np.hstack((a,b)),np.hstack((a,b)))))
print(np.vstack((np.vstack((a,b)),np.vstack((a,b)))))

[1 2 3 2 3 4]
[[1 2 3]
 [2 3 4]]
[1 2 3 2 3 4 1 2 3 2 3 4]
[[1 2 3 1 2 3]
 [2 3 4 2 3 4]]
[[1 2 3 2 3 4]
 [1 2 3 2 3 4]]
[[1 2 3]
 [2 3 4]
 [1 2 3]
 [2 3 4]]


In [48]:
a = [[1, 5],
 [3, 7],
 [4, 9]]

# print(np.reshape(a, -1))
# print(np.reshape(a,(-1,3)))



b = [np.array(i) for i in [[7, 13, 14], [18, 10, 17], [11, 12, 19], [16, 6, 1], [5, 8, 4, 3]]]
print(b)

[array([ 7, 13, 14]), array([18, 10, 17]), array([11, 12, 19]), array([16,  6,  1]), array([5, 8, 4, 3])]
