In [2]:
import numpy as np, pandas

#Classes overview (instance methods, class methods, static methods)
from IPython.display import display,HTML
display(HTML('''
<h3>Data Science</h3>
<h4>Numpy</h4>
<h4>Pandas</h4>
''')) 

In [3]:
heights = [1,2,3,4,5,6]
#print(heights*2.54)   # TypeError: can't multiply sequence by non-int of type 'float'

print(np.array(heights)*2.54) # homogeneous



[ 2.54  5.08  7.62 10.16 12.7  15.24]


In [4]:
# Numpy arithmetic operations

display(HTML('''
<h3>Numpy arithmetic operations</h3>

''')) 

list_1 = [1,2,3,4]
list_2 = [7,8,9,0]

print(list_1 + list_2)
print(np.array(list_1) + np.array(list_2))
np_1 = np.array(list_1)

print(np_1*0.0254)
print(len(np_1))
print(np_1.size)
print(np_1.shape)
print(np_1/2)
print(np_1//2)
print(np_1**2)
print(np_1+2)
print(np_1-2)
print(np_1)

[1, 2, 3, 4, 7, 8, 9, 0]
[ 8 10 12  4]
[0.0254 0.0508 0.0762 0.1016]
4
4
(4,)
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]
[3 4 5 6]
[-1  0  1  2]
[1 2 3 4]


In [5]:
display(HTML('''
<h3>Indexing, splitting, slicing</h3>

''')) 
print(np_1[0])
print(np_1[-0])
print(np_1[-----1])
print(np_1[---+---1])
print(np_1[-4:-1])
print(np_1[-4:])
print(np_1[::-2])

1
1
4
2
[1 2 3]
[1 2 3 4]
[4 2]


In [6]:
display(HTML('''
<h3>Conditional sub-setting arrays</h3>
''')) 

print(np_1<3)
print(np_1[np_1<3])
print((np_1<3).size)

[ True  True False False]
[1 2]
4


In [7]:
display(HTML('''
<h3>Numpy functions</h3>
''')) 

print(max(np_1))
print(min(np_1))
print((np_1).min())
print((np_1).max())
print((np_1).mean())
print(type(np_1))

4
1
1
4
2.5
<class 'numpy.ndarray'>


In [8]:
display(HTML('''
<h3>Multidimensional arrays</h3>
''')) 

players = [[12,23],[23,34],[34,45],[45,56],[56,67],[67,78],[78,89]]
print(np.array(players))
players = [(12,23),(23,34),(34,45),(45,56),(56,67),(67,78),(78,89)]
print(np.array(players))
players0 = [{12,23},{23,34},{34,45},{45,56},{56,67},{67,78},{78,89}]
print(np.array(players0))

[[12 23]
 [23 34]
 [34 45]
 [45 56]
 [56 67]
 [67 78]
 [78 89]]
[[12 23]
 [23 34]
 [34 45]
 [45 56]
 [56 67]
 [67 78]
 [78 89]]
[{12, 23} {34, 23} {34, 45} {56, 45} {56, 67} {67, 78} {89, 78}]


In [9]:
display(HTML('''
<h3>Multidimensional arrays (continued)</h3>
''')) 


players1 = [{12,23},{23,34},(34,45),(45,56),(56,67),(67,78),(78,89)]
print(np.array(players1))

[{12, 23} {34, 23} (34, 45) (45, 56) (56, 67) (67, 78) (78, 89)]


C:\Users\Padmaja\AppData\Local\Temp\ipykernel_24684\3558071355.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array(players1))


In [10]:
np_players = np.array(players)
print(np_players.ndim)  # dimension
print(np_players.dtype)
print(np_players.astype('int64').dtype)  # to change dtype
print(np_players.itemsize)
print(np_players)
np_players_64 = np_players.astype('int64')
print(np_players_64.itemsize)

print(np_players_64*[2,5])

2
int32
int64
4
[[12 23]
 [23 34]
 [34 45]
 [45 56]
 [56 67]
 [67 78]
 [78 89]]
8
[[ 24 115]
 [ 46 170]
 [ 68 225]
 [ 90 280]
 [112 335]
 [134 390]
 [156 445]]


In [11]:
print(np_players_64[:,:2]) 
print(np_players_64[:,:2]>22) 
print(np_players_64[:,:2]>[22,32]) 

[[12 23]
 [23 34]
 [34 45]
 [45 56]
 [56 67]
 [67 78]
 [78 89]]
[[False  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
[[False False]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
