In [6]:
import numpy as np, pandas

#Classes overview (instance methods, class methods, static methods)
from IPython.display import display,HTML
display(HTML('''
<h3>Data Science</h3>
<h4>Numpy</h4>
<h4>Pandas</h4>
''')) 

In [8]:
heights = [1,2,3,4,5,6]
#print(heights*2.54)   # TypeError: can't multiply sequence by non-int of type 'float'

print(np.array(heights)*2.54) # homogeneous



[ 2.54  5.08  7.62 10.16 12.7  15.24]


In [46]:
# Numpy arithmetic operations

display(HTML('''
<h3>Numpy arithmetic operations</h3>

''')) 

list_1 = [1,2,3,4]
list_2 = [7,8,9,0]

print(list_1 + list_2)
print(np.array(list_1) + np.array(list_2))
np_1 = np.array(list_1)

print(np_1*0.0254)
print(len(np_1))
print(np_1.size)
print(np_1.shape)
print(np_1/2)
print(np_1//2)
print(np_1**2)
print(np_1+2)
print(np_1-2)
print(np_1)

[1, 2, 3, 4, 7, 8, 9, 0]
[ 8 10 12  4]
[0.0254 0.0508 0.0762 0.1016]
4
4
(4,)
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]
[3 4 5 6]
[-1  0  1  2]
[1 2 3 4]


In [53]:
display(HTML('''
<h3>Indexing, splitting, slicing</h3>

''')) 
print(np_1[0])
print(np_1[-0])
print(np_1[-----1])
print(np_1[---+---1])
print(np_1[-4:-1])
print(np_1[-4:])
print(np_1[::-2])

1
1
4
2
[1 2 3]
[1 2 3 4]
[4 2]


In [55]:
display(HTML('''
<h3>Conditional sub-setting arrays</h3>
''')) 

print(np_1<3)
print(np_1[np_1<3])
print((np_1<3).size)

[ True  True False False]
[1 2]
4


In [52]:
display(HTML('''
<h3>Numpy functions</h3>
''')) 

print(max(np_1))
print(min(np_1))
print((np_1).min())
print((np_1).max())
print((np_1).mean())

4
1
1
4
2.5
